// Generated by CoffeeScript 1.12.5
var bar, baz, foo, portal, sync;

sync = require('./src/main.js');

foo = {};

bar = {};

baz = {};

portal = new sync.VPortal([[foo, 'ham'], [bar, 'spam'], [baz, 'eggs']]);

foo.ham = 100;

console.log(foo.ham + ", " + bar.spam + ", " + baz.eggs);

portal.desync();

foo.ham = 10;

bar.spam = 'Do dolor esse tempor';

baz.eggs = {
  x: 50
};

console.log(foo.ham + ", " + bar.spam + ", " + baz.eggs);
