// Generated by CoffeeScript 1.12.5
var coffee, gulp, mocha, rename, uglify;

gulp = require('gulp');

coffee = require('gulp-coffee');

uglify = require('gulp-uglify');

mocha = require('gulp-mocha');

rename = require('gulp-rename');

gulp.task('tests', function() {
  return gulp.src('test.js', {
    read: false
  }).pipe(mocha());
});

gulp.task('pack', function() {
  return gulp.src('src/main.coffee').pipe(coffee({
    bare: true
  })).pipe(rename('build.js')).pipe(gulp.dest('build')).pipe(rename('build.min.js')).pipe(uglify()).pipe(gulp.dest('build'));
});

gulp.task('build', ['tests', 'pack']);

gulp.task('default', ['build']);
