// Generated by CoffeeScript 1.12.5
var VPortal, _,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

_ = require('./lodash.custom.min.js');

VPortal = (function() {
  return VPortal = (function(superClass) {
    extend(VPortal, superClass);

    function VPortal(args) {}

    return VPortal;

  })(Object);
})()[0];

module.exports.VPortal = VPortal;
